#!/bin/bash
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
cat <(git ls-files) <(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") |
    ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
